# Generated by Django 4.0.4 on 2022-10-18 16:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_Name', models.CharField(max_length=100)),
                ('clinic_logo', models.ImageField(upload_to='clinic_logo')),
                ('pysician_name', models.CharField(max_length=80)),
                ('pysician_Contact', models.CharField(max_length=80)),
                ('patient_first_name', models.CharField(max_length=80)),
                ('patient_last_name', models.CharField(max_length=80)),
                ('patient_dob', models.DateField(null=True)),
                ('patient_contact', models.CharField(max_length=50)),
                ('chief_complaint', ckeditor.fields.RichTextField()),
                ('consultation_note', ckeditor.fields.RichTextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
